yolo_model:

  config_file:
    name: yolov4-custom-sea.cfg
  weight_file:
    name: yolov4-custom-land-1900.weights
  threshold:
    value: 0.1
  detection_classes:
    names:
      - G
      - R
      - W
      - H
